
/**
 * DO NOT EDIT THIS FILE
 */

//
#include <bitset>
#include <fstream>
#include <functional>
#include <iostream>
#include <string>
#include <tuple>
#include <vector>


//
#include "MyHashTable.hpp"
#include "MyRolodex.hpp"
#include "puhp-tests/PuhPTests.hpp"


//
using std::cout, std::cin, std::endl;
using std::ifstream;
using std::string, std::to_string;
using std::tuple;
using std::vector;

//
typedef int LEADERBOARD_VTYPE;

//
using PuhPTests::Tests;
using PuhPTests::Test;
using PuhPTests::OutputCapture;
using PuhPTests::Timer;
using PuhPTests::Complexity;
using PuhPTests::Random;
using PuhPTests::Leaderboard;
using PuhPTests::LeaderboardSortDirection;


//	Include student stuff
using CPSC131::MyHashTable::MyHashTable;
using CPSC131::MyRolodex::MyRolodex;
using CPSC131::MyRolodex::Address;


//	PROTO
void preventPrototypeTampering();
void loadWords();
string increaseWordLength(string word);
MyHashTable<string> createWordTable(size_t capacity = 1000000, bool longWords = false, bool shortDict = false);
std::vector<std::string> makeTinyWordVariants(const std::string& word);

template<class T>
bool checkTablesEqual(const MyHashTable<T>& t1, const MyHashTable<T>& t2, bool do_throw = false);

std::tuple<unsigned long long int, unsigned long long int> computeHashOutputSimilarities(
	const std::string& word,
	const std::vector<std::string>& variants,
	unsigned long long int (MyHashTable<int>::* f)(std::string) const
);

//
void testHashingFunctions(Tests& tests);
void testTableManipulation(Tests& tests);
void testTableComplexity(Tests& tests);
void testRolodex(Tests& tests);
void testCopyAssignment(Tests& tests);
void testMemoryLeaks(Tests& tests);
void testLeaderboard(Tests& tests);


//	Globals
string g_words_filename = "words.txt";
vector<string> g_words;


//
int main()
{
	//
	Tests tests(50);
	
	//
	preventPrototypeTampering();
	loadWords();
	
	//
	std::vector<std::function<void(Tests&)>> fs = {
		testHashingFunctions,
		testCopyAssignment,
		testTableManipulation,
		testTableComplexity,
		testRolodex,
		testMemoryLeaks,
		testLeaderboard,
	};
	
	//
	for ( auto f : fs ) {
		f(tests);
	}
	
	//
	tests.setResultsFileName("results-cpp.json");
	tests.run(true);
	
	//
	cout << "Tests complete" << endl;
	
	return 0;
}


//
void preventPrototypeTampering()
{
	//	MyHashTable
	{
		//
		typedef int T;
		typedef MyHashTable<T> Table;
		
		//	Hashing functions
		{
			unsigned long long int (Table::* a)(std::string) const;
			a = &Table::hash;
			a = &Table::myCustomHashFunction1;
			a = &Table::myCustomHashFunction2;
			a = &Table::myCustomHashFunction3;
			a = &Table::myCustomHashFunction4;
			a = &Table::midSquareHash;
			if (a) {}
		}
		
		//	Getters
		{
			size_t (Table::* a)(void) const;
			a = &Table::capacity;
			a = &Table::size;
			a = &Table::n_collisions;
			if (a) {}
			
			bool (Table::* b)(std::string) const;
			b = &Table::exists;
			if (b) {}
			
			bool (Table::* c)(void) const;
			c = &Table::empty;
			if (c) {}
			
			T& (Table::* d)(std::string) const;
			d = &Table::get;
			if (d) {}
			
			std::forward_list<std::string> (Table::*e)(bool) const;
			e = &Table::getAllKeys;
			if (e) {}
		}
		
		//	Setters
		{
			void (Table::* a)(std::string, int);
			a = &Table::add;
			if (a) {}
			
			void (Table::* b)(std::string);
			b = &Table::remove;
			if (b) {}
			
			void (Table::* c)(void);
			c = &Table::clear;
			if (c) {}
		}
		
		//	Misc helpers
		{
			//	Becaue ullToBitString is a static method,
			//	the pointer wants me to treat it as a global function, basically
			std::string (* a)(unsigned long long int);
			a = &Table::ullToBitString;
			if (a) {}
		}
	}
	
	//	MyRolodex
	{
		typedef MyRolodex R;
		
		bool (R::* a)(std::string) const;
		a = &R::exists;
		if (a) {}
		
		void (R::* b)(std::string);
		b = &R::remove;
		if (b) {}
		
		// Having trouble binding overloaded ::add, so just letting it be
		
		Address (R::* c)(std::string) const;
		c = &R::get;
		if (c) {}
		
		void (R::* d)(void);
		d = &R::clear;
		if (d) {}
		
		bool (R::* e)(void);
		e = &R::empty;
		if (e) {}
		
		size_t (R::* f)(void);
		f = &R::size;
		if (f) {}
	}
}


//
void loadWords()
{
	ifstream f(g_words_filename);
	if ( !f ) {
		throw std::runtime_error("Unable to load words file: " + g_words_filename);
	}
	
	g_words.clear();
	string word;
	while ( true )
	{
		f >> word;
		if ( f.eof() ) {
			break;
		}
		g_words.push_back(word);
	}
	
	//
	cout << "Loaded " << g_words.size() << " words from " << g_words_filename << endl;
	if ( g_words.size() != 102774 ) {
		throw std::runtime_error("Expected 102774 words from the word list but got " + to_string(g_words.size()));
	}
}


//
string increaseWordLength(string word)
{
	//
	word += word;
	word += word;
	word += word;
	word += word;
	
	return word;
}


//
MyHashTable<string> createWordTable(size_t capacity, bool longWords, bool shortDict)
{
	//
	MyHashTable<string> table(capacity);
	
	//
	size_t i = 0;
	for ( auto word : g_words ) {
		
		//
		if ( longWords == true ) {
			word = increaseWordLength(word);
		}
		
		//
		table.add(word, "Value for word: " + word);
		i++;
		
		//
		if ( shortDict == true && i >= 1000 ) {
			break;
		}
	}
	
	return table;
}

//
std::vector<std::string> makeTinyWordVariants(const std::string& word)
{
	std::vector<std::string> variants;
	std::string variant;
	
	//
	for ( size_t i = 0; i < word.size(); i++ ) {
		
		//
		char c = word[i];
		
		//
		if ( isalpha( c ) ) {
			if ( islower( c ) && c > 'a' ) {
				variant = word;
				variant[i] = c -= 1;
				variants.push_back(variant);
			}
			if ( islower( c ) && c < 'z' ) {
				variant = word;
				variant[i] = c += 1;
				variants.push_back(variant);
			}
			if ( isupper( c ) && c > 'A' ) {
				variant = word;
				variant[i] = c -= 1;
				variants.push_back(variant);
			}
			if ( isupper( c ) && c < 'Z' ) {
				variant = word;
				variant[i] = c += 1;
				variants.push_back(variant);
			}
		}
	}
	
	return variants;
}


//
template<class T>
bool checkTablesEqual(const MyHashTable<T>& t1, const MyHashTable<T>& t2, bool do_throw)
{
	if ( t1.size() != t2.size() ) {
		if ( do_throw ) {
			throw std::runtime_error("checkTablesEqual() - Tables have different size");
		}
		return false;
	}
	if ( t1.capacity() != t2.capacity() ) {
		if ( do_throw ) {
			throw std::runtime_error("checkTablesEqual() - Tables have different capacity");
		}
		return false;
	}
	if ( t1.n_collisions() != t2.n_collisions() ) {
		if ( do_throw ) {
			throw std::runtime_error("checkTablesEqual() - Tables have different number of collisions");
		}
		return false;
	}
	
	auto allKeys1 = t1.getAllKeys(true);
	auto allKeys2 = t2.getAllKeys(true);
	
	size_t sz = t1.size();
	auto allKeys1_itr = allKeys1.begin();
	auto allKeys2_itr = allKeys2.begin();
	for ( size_t i = 0; i < sz; i++ ) {
		
		auto key1 = (*allKeys1_itr);
		auto key2 = (*allKeys2_itr);
		if ( key1 != key2 ) {
			if ( do_throw ) {
				throw std::runtime_error("checkTablesEqual() - Tables have different keys at index " + std::to_string(i) + " => " + key1 + ":" + key2);
			}
			return false;
		}
		
		auto v1 = t1.get(key1);
		auto v2 = t2.get(key2);
		if ( v1 != v2 ) {
			if ( do_throw ) {
				throw std::runtime_error("checkTablesEqual() - Tables have different values at index " + std::to_string(i) + " => " + v1 + ":" + v2);
			}
			return false;
		}
		
		allKeys1_itr++;
		allKeys2_itr++;
	}
	
	return true;
}


//
std::tuple<unsigned long long int, unsigned long long int> computeHashOutputSimilarities(
	const std::string& word,
	const std::vector<std::string>& variants,
	unsigned long long int (MyHashTable<int>::* f)(std::string) const
)
{
	MyHashTable<int> table;
	std::tuple<unsigned long long int, unsigned long long int> result;
	
	unsigned long long int best_possible = sizeof(unsigned long long int) * variants.size();
	unsigned long long int actual = 0;
	
	/*
	cout << "computeHashOutputSimilarities() - \"" << word << "\"";
	for ( const auto& variant : variants ) {
		cout << " " << variant;
	}
	cout << endl;
	*/
	
	//
	auto word_hash = (table.*f)(word);
	
	//
	for ( auto& variant : variants) {
		
		auto variant_hash = (table.*f)(variant);
		
		//	XOR trick to count number of bits that are different
		std::bitset<64> xor_result = word_hash ^ variant_hash;
		actual += xor_result.count();
	}
	
	//
	//std::bitset<64> word_bits( word );
	//std::cout << "Word \"" << word << "\": " << word_bits.to_string() << std::endl;
	
	std::get<0>(result) = actual;
	std::get<1>(result) = best_possible;
	
	/*
	cout << "> Actual:     " << actual << endl;
	cout << "> Possible:   " << best_possible << endl;
	*/
	
	if ( actual > best_possible ) {
		throw std::runtime_error("lul wot");
	}
	
	return result;
}


//
void testHashingFunctions(Tests& tests)
{
	//
	auto t = tests.createTest("Hashing");
	
	t->setFixedPointsPossible(10);
	t->setNormalizedPointsPossibleTarget(5);
	
	//	Check that the modified midSquare hash function produces in-bounds codes
	{
		//
		MyHashTable<int> table1(10000), table2(1000), table3(10);
		
		//
		t->log("Checking midSquare hash stays in-bounds");
		for ( auto word : g_words ) {
			
			//
			word = increaseWordLength(word);
			
			//
			unsigned long long int
				code1 = table1.midSquareHash(word),
				code2 = table2.midSquareHash(word),
				code3 = table3.midSquareHash(word)
				;
			
			//
			if (code1 >= table1.capacity() ) {
				t->assertTrue(code1 < table1.capacity(), 0, "Modified midSquare hash code (" + to_string(code1) + ") should be in-bounds of table capacity (" + to_string(table1.capacity()) + ")");
			}
			if (code2 >= table1.capacity() ) {
				t->assertTrue(code2 < table2.capacity(), 0, "Modified midSquare hash code (" + to_string(code2) + ") should be in-bounds of table capacity (" + to_string(table2.capacity()) + ")");
			}
			if (code3 >= table1.capacity() ) {
				t->assertTrue(code3 < table3.capacity(), 0, "Modified midSquare hash code (" + to_string(code3) + ") should be in-bounds of table capacity (" + to_string(table3.capacity()) + ")");
			}
		}
		t->assertTrue(true, 2, "Modified midSquare hash code bounds-checks were successful");
	}
	
	//	Test the modified midSquare hashing function
	{
		//
		MyHashTable<int> table1(10000), table2(1000), table3(100);
		
		//	Test some key/value combos
		vector<tuple<string, unsigned long long int, unsigned long long int, unsigned long long int>> combos;
		combos.push_back({"a",										4976ULL,	976ULL,		76ULL});
		combos.push_back({"aa",										2933ULL,	933ULL,		33ULL});
		combos.push_back({"zz",										6508ULL,	508ULL,		8ULL});
		combos.push_back({"iuI1U11W1EH3F3I4U4b4w4eiun",				7884ULL, 	884ULL,		84ULL});
		combos.push_back({"2d8dnfqwef23f f23f23 2f4a3c 3a34 g",		1935ULL,	935ULL,		35ULL});
		combos.push_back({"2d8dnfqwef23f f23f23 2f4a3c 3a34 h",		8151ULL,	151ULL,		51ULL});
		combos.push_back({"2d8dnfqwef23f f23f23 2f4a3c 3a34 gg",	8820ULL,	820ULL,		20ULL});
		combos.push_back({"oO(@#*(*FJjfhfhf fh  hh  h hh     ",		436ULL,		436ULL,		36ULL});
		combos.push_back({"wefi2q3",								209ULL,		209ULL,		9ULL});
		combos.push_back({"242",									9222ULL,	222ULL,		22ULL});
		combos.push_back({"11110000",								7828ULL,	828ULL,		28ULL});
		
		//
		t->log("Checking midSquare hash produces correct results");
		
		//
		unsigned long long int hashCode1_actual, hashCode2_actual, hashCode3_actual;
		for ( auto tup : combos) {
			
			//
			string word = std::get<0>(tup);
			unsigned long long int hashCode1_expected = std::get<1>(tup);
			unsigned long long int hashCode2_expected = std::get<2>(tup);
			unsigned long long int hashCode3_expected = std::get<3>(tup);
			
			//
			string word_longer = increaseWordLength(word);
			
			//
			hashCode1_actual = table1.midSquareHash(word_longer);
			hashCode2_actual = table2.midSquareHash(word_longer);
			hashCode3_actual = table3.midSquareHash(word_longer);
			
			//	Check all codes are correct
			if ( hashCode1_actual != hashCode1_expected ) {
				t->assertEqual(hashCode1_actual, hashCode1_expected, 0, "Checking midSquareHash for: " + word_longer + " (" + word + ")");
			}
			if ( hashCode2_actual != hashCode2_expected ) {
				t->assertEqual(hashCode2_actual, hashCode2_expected, 0, "Checking midSquareHash for: " + word_longer + " (" + word + ")");
			}
			if ( hashCode3_actual != hashCode3_expected ) {
				t->assertEqual(hashCode3_actual, hashCode3_expected, 0, "Checking midSquareHash for: " + word_longer + " (" + word + ")");
			}
		}
		t->assertTrue(true, 5, "Modified midSquare hash code output tests passed");
	}
	
	//	Check that the custom hash functions produce in-bounds codes
	{
		//
		MyHashTable<int> table1(10000), table2(1000), table3(10);
		
		//
		t->log("Checking that custom hash functions produce in-bounds codes.");
		
		//
		for ( size_t i = 0; i < g_words.size(); i++ ) {
			
			//	No need to do the full dict
			if ( i == 1000 ) {
				break;
			}
			
			//
			auto word = increaseWordLength(g_words[i]);
			
			//
			unsigned long long int
				code11 = table1.myCustomHashFunction1(word),
				code12 = table1.myCustomHashFunction2(word),
				code13 = table1.myCustomHashFunction3(word),
				code14 = table1.myCustomHashFunction4(word),
				
				code21 = table2.myCustomHashFunction1(word),
				code22 = table2.myCustomHashFunction2(word),
				code23 = table2.myCustomHashFunction3(word),
				code24 = table2.myCustomHashFunction4(word),
				
				code31 = table3.myCustomHashFunction1(word),
				code32 = table3.myCustomHashFunction2(word),
				code33 = table3.myCustomHashFunction3(word),
				code34 = table3.myCustomHashFunction4(word)
				;
			
			//
			vector<tuple<MyHashTable<int>&, unsigned long long int, unsigned long long int, unsigned long long int, unsigned long long int>> items = {
				{table1, code11, code12, code13, code14},
				{table2, code21, code22, code23, code24},
				{table3, code31, code32, code33, code34},
			};
			for ( auto tup : items ) {
				
				//
				auto table = std::get<0>(tup);
				auto code1 = std::get<1>(tup);
				auto code2 = std::get<2>(tup);
				auto code3 = std::get<3>(tup);
				auto code4 = std::get<4>(tup);
				
				//
				if ( code1 >= table.capacity() ) {
					t->assertTrue(code1 < table.capacity(), 0, "Custom hash code 1 (" + to_string(code1) + ") should be in-bounds of table capacity (" + to_string(table.capacity()) + ")");
				}
				if ( code2 >= table.capacity() ) {
					t->assertTrue(code2 < table.capacity(), 0, "Custom hash code 2 (" + to_string(code2) + ") should be in-bounds of table capacity (" + to_string(table.capacity()) + ")");
				}
				if ( code3 >= table.capacity() ) {
					t->assertTrue(code3 < table.capacity(), 0, "Custom hash code 3 (" + to_string(code3) + ") should be in-bounds of table capacity (" + to_string(table.capacity()) + ")");
				}
				if ( code4 >= table.capacity() ) {
					t->assertTrue(code4 < table.capacity(), 0, "Custom hash code 4 (" + to_string(code4) + ") should be in-bounds of table capacity (" + to_string(table.capacity()) + ")");
				}
			}
		}
		t->assertTrue(true, 2, "Custom hash code bounds-checks were successful");
	}
	
	//	Check that the custom hash functions are deterministic and not random, lol
	{
		//
		MyHashTable<int> table(100000);
		
		//
		for ( auto word : g_words ) {
			
			//
			auto code1 = table.myCustomHashFunction1(word);
			auto code2 = table.myCustomHashFunction2(word);
			auto code3 = table.myCustomHashFunction3(word);
			auto code4 = table.myCustomHashFunction4(word);
			
			//
			if ( code1 != table.myCustomHashFunction1(word) ) {
				t->assertEqual(code1, table.myCustomHashFunction1(word), 0, "Custom code 1 should be deterministic!");
			}
			if ( code2 != table.myCustomHashFunction2(word) ) {
				t->assertEqual(code2, table.myCustomHashFunction2(word), 0, "Custom code 2 should be deterministic!");
			}
			if ( code3 != table.myCustomHashFunction3(word) ) {
				t->assertEqual(code3, table.myCustomHashFunction3(word), 0, "Custom code 3 should be deterministic!");
			}
			if ( code4 != table.myCustomHashFunction4(word) ) {
				t->assertEqual(code4, table.myCustomHashFunction4(word), 0, "Custom code 4 should be deterministic!");
			}
		}
		t->assertTrue(true, 1, "Extra point for not trying to hack the Leaderboard");
	}
}

//
void testTableManipulation(Tests& tests)
{
	//
	auto t = tests.createTest("Table Manip");
	
	t->setFixedPointsPossible(23);
	t->setNormalizedPointsPossibleTarget(5);
	
	//	Fill the table with words
	{
		//
		t->log("Filling table 1 (10000000) with " + to_string(g_words.size()) + " words...");
		auto table1 = createWordTable(10000000, false);
		
		//
		t->log("Filling table 2 (1000000) with " + to_string(g_words.size()) + " words...");
		auto table2 = createWordTable(1000000, false);
		
		//
		t->log("Filling table 3 (1000) with " + to_string(g_words.size()) + " words...");
		auto table3 = createWordTable(1000, false);
		
		//	Check the capacity, size
		t->assertEqual(table1.capacity(),	10000000ULL, 1, "Checking correct capacity hash table");
		t->assertEqual(table1.size(),		102774ULL, 1, "Checking correct size of hash table after adding dictionary");
		
		//	Check number of collisions
		t->assertEqual(table1.n_collisions(), 6249ULL, 1, "Checking correct number of collisions in hash table (capacity " + to_string(table1.capacity()) + ") after adding dictionary");
		t->assertEqual(table2.n_collisions(), 10317ULL, 1, "Checking correct number of collisions in hash table (capacity " + to_string(table2.capacity()) + ") after adding dictionary");
		t->assertEqual(table3.n_collisions(), 101774ULL, 1, "Checking correct number of collisions in hash table (capacity " + to_string(table3.capacity()) + ") after adding dictionary");
	}
	
	//	Check add/exist/get/remove
	{
		//
		MyHashTable<int> table;
		Random r;
		
		//
		for ( size_t i = 0; i < 1000; i++ ) {
			
			//
			int rKey = r.get(0, 1000000);
			int value = r.get(0, 1000000);
			
			//
			string key = "zzzz_" + to_string(rKey) + "_" + to_string(value) + "_" + to_string(i);
			
			//	Entry shouldn't exist, at first
			if ( table.exists(key) ) {
				t->assertFalse(table.exists(key), 0, "Key \"" + key + "\" should not already exist!");
			}
			
			//	Add to the table, and make sure it does exist now
			table.add(key, value);
			if ( !table.exists(key) ) {
				t->assertTrue(table.exists(key), 0, "Key \"" + key + "\" should now exist!");
			}
			
			//	Get the value and make sure it is correct
			if ( table.get(key) != value ) {
				t->assertEqual(table.get(key), value, 0, "Key \"" + key + "\" should have the value: " + to_string(value));
			}
			
			//	Remove, and make sure it no longer exists
			table.remove(key);
			if ( table.exists(key) ) {
				t->assertFalse(table.exists(key), 0, "Key \"" + key + "\" should not exist after removal!");
			}
		}
		t->assertTrue(true, 5, "Add/exist/get/remove tests seem to have passed");
	}
	
	//	Check collisions accurately recorded
	{
		//
		t->log("Checking collisions on a table of capacity=1");
		auto table = createWordTable(1, true, true);
		
		//
		t->assertEqual(table.n_collisions(), 999UL, 1, "Table of capacity=1 should be nothing but collisions");
	}
	
	//	Clear a table
	{
		//
		auto table = createWordTable(1000000);
		if ( table.empty() ) {
			t->assertFalse(table.empty(), 0, "Checking if word table thinks it is empty");
		}
		
		//
		t->log("Clearing a table item by item");
		size_t wantedSize = table.size();
		size_t j = wantedSize / 2;
		for ( size_t i = 0; i < j; i++ ) {
			
			//
			table.remove(g_words[i]);
			
			//
			wantedSize--;
			if ( table.size() != wantedSize ) {
				t->assertEqual(table.size(), wantedSize, 0, "Size after removing word " + g_words[i] + " should be: " + to_string(wantedSize));
			}
		}
		t->assertTrue(true, 1, "Check size changes as table is progressively emptied");
		
		//
		t->log("Clearing the rest of the table instantly with clear()");
		table.clear();
		t->assertTrue(table.empty(), 1, "Table should be empty() after clearing");
	}
	
	//	Check double-add exception
	t->assertException(
		[]()
		{
			//
			auto table = createWordTable();
			table.add("hello", "Whoops, duplicate value for word: Hello");
			
		}, 1, "Attempting to add an existing key should throw an exception"
	);
	
	//	Check remove exception
	t->assertException(
		[]()
		{
			//
			MyHashTable<int> table;
			
			//
			table.remove("Does not exist");
			
		}, 1, "Attempting to remove key that doesn't exist should throw an exception"
	);
	
	//	Check get exception
	t->assertException(
		[]()
		{
			//
			MyHashTable<int> table;
			
			//
			table.get("Does not exist");
			
		}, 1, "Attempting to get value for key that doesn't exist should throw an exception"
	);
	
	//	Check that resizing a table doesn't destroy data
	//	(but does change the number of collisions)
	{
		//	Start with table of 1m
		auto table = createWordTable(1000000);
		
		//	Check n_collissions
		t->assertEqual(table.n_collisions(), 10317ULL, 0, "Table of capacity " + to_string(table.capacity()) + " should have resulted in 10317 collisions");
		
		//	Change capacity to only 100k
		table.setCapacity(100000);
		
		//	Check n_collisions again
		t->assertEqual(table.capacity(), 100000ULL, 0, "Check that capacity was actually modified");
		t->assertEqual(table.n_collisions(), 40810ULL, 1, "Table of capacity " + to_string(table.capacity()) + " should have resulted in 40810 collisions");
		
		//
		t->assertTrue(true, 3, "Table resize seems to be working (n_collisions).");
		
		//	Make sure every item survived the resize
		for ( auto word : g_words ) {
			if ( !table.exists(word) ) {
				t->assertTrue(table.exists(word), 0, "Word is missing after table resize: " + word);
			}
		}
		t->assertTrue(true, 3, "Table resize seems to be working (data survival).");
	}
}

void testTableComplexity(Tests& tests)
{
	//
	auto t = tests.createTest("Complexity");
	
	t->setFixedPointsPossible(4);
	t->setNormalizedPointsPossibleTarget(5);
	
	//	Fast vs. Slow
	{
		//	Create a fast table
		Timer timer1;
		auto table1 = createWordTable(100000, false, false);
		timer1.stop();
		
		//	Create a slow table
		Timer timer2;
		auto table2 = createWordTable(100, false, false);
		timer2.stop();
		
		//	The fast table should have been way faster to populate than the slow table
		t->assertTrue(
			timer1.microseconds() * 5 < timer2.microseconds(), 1,
			"Larger table (less collisions) should be much faster to populate than a smaller table (more collisions). Larger table took " + timer1.milliseconds_s()
				+ "ms while smaller table took " + timer2.milliseconds_s() + "ms."
				+ " Collisions = " + to_string(table1.n_collisions()) + " vs. " + to_string(table2.n_collisions()) + "."
				+ " Factor = " + to_string(static_cast<double>(timer2.microseconds()) / static_cast<double>(timer1.microseconds()))
		);
		
		//	The fast table should be much faster to access than the slow table
		Timer timer1_access;
		for ( auto word : g_words ) {
			table1.get(word);
		}
		timer1_access.stop();
		//
		Timer timer2_access;
		for ( auto word : g_words ) {
			table2.get(word);
		}
		timer2_access.stop();
		t->assertTrue(timer1_access.microseconds() * 5 < timer2_access.microseconds(), 1, "Larger table (less collisions) should be much faster to access than a smaller table (more collisions)");
	}
	
	//	Insertion and Access: Constant time for a large table
	{
		//
		MyHashTable<string> table(10000000);
		Timer timer1, timer2, timer3, timer4;
		Complexity complexity;
		
		//	Check Insertion
		for ( size_t i = 0; i < g_words.size(); i++ ) {
			table.add(g_words[i], g_words[i]);
			if ( i == 10000 ) {
				timer2.start();
			}
		}
		timer1.stop();
		timer2.stop();
		t->log("Time for timer1: " + to_string(timer1.microseconds()) + "; Time for timer2: " + to_string(timer2.microseconds()));
		t->assertTrue(complexity.checkConstantTime(timer1, 10000, timer2, g_words.size()), 1, "Add/Insert to a large-enough table should be about constant time");
		
		//	Check Insertion
		timer3.start();
		for ( size_t i = 0; i < g_words.size(); i++ ) {
			table.get(g_words[i]);
			if ( i == 10000 ) {
				timer4.start();
			}
		}
		timer3.stop();
		timer4.stop();
		t->log("Time for timer3: " + to_string(timer3.microseconds()) + "; Time for timer4: " + to_string(timer4.microseconds()));
		t->assertTrue(complexity.checkConstantTime(timer3, 10000, timer4, g_words.size()), 1, "Access with a large-enough table should be about constant time");
	}
}


//
void testRolodex(Tests& tests)
{
	//
	auto t = tests.createTest("Rolodex");
	
	t->setFixedPointsPossible(5);
	t->setNormalizedPointsPossibleTarget(5);
	
	//
	std::shared_ptr<MyRolodex> dex(new MyRolodex);
	
	//
	std::shared_ptr<Address> larry_address(new Address);
	larry_address->line1 = "1212122 Lane Road";
	larry_address->line2 = "";
	larry_address->city = "Fullerton";
	larry_address->state = "CA";
	larry_address->zip = 92831;
	larry_address->country = "US";
	
	//	Add to rolodex normally
	t->assertNoException(
		[t, dex, larry_address]()
		{
			dex->add("Gary", "1212121 Lane Way", "", "Fullerton", "CA", 92831, "US");
			dex->add("Larry", *larry_address);
			dex->add("Harry", "1212123 Lane Place", "", "Fullerton", "CA", 92831, "US");
			dex->add("Sally", "1212124 Lane Blvd", "", "Fullerton", "CA", 92831, "US");
			
		}, 1, "Add to the Rolodex"
	);
	t->run();
	
	//	Check stuff
	t->assertNoException(
		[t, dex, larry_address]()
		{
			t->assertEqual(dex->size(), 4UL, 0, "Check size");
			t->assertTrue(dex->exists("Larry"), 0, "Check that an added entry does exist");
			t->assertTrue(dex->get("Larry") == *larry_address, 0, "Check fetch from the Rolodex. Expected <<<" + larry_address->toString() + ">>> and found <<<" + dex->get("Larry").toString() + ">>>");
			t->assertTrue(dex->get("Gary") != *larry_address, 0, "Check not-equal fetch from the Rolodex. Expected <<<" + dex->get("Gary").toString() + ">>> to be different from <<<" + larry_address->toString() + ">>>");
		}, 1, "Check stuff after add"
	);
	t->run();
	
	//	Make sure we can remove
	t->assertNoException(
		[t, dex, larry_address]()
		{
			//	Remove
			dex->remove("Larry");
			t->assertFalse(dex->exists("Larry"), 0, "Check that a deleted entry no longer exists");
			
		}, 1, "Removing a valid entry"
	);
	t->run();
	
	//	Expect an exception when deleting something that doesn't exist
	t->assertException(
		[dex]()
		{
			dex->remove("Busey");
			
		}, 1, "Delete an entry that doesn't exist from the Rolodex"
	);
	t->run();
	
	//	Expect an exception when adding duplicates
	t->assertException(
		[]()
		{
			//
			MyRolodex dex;
			
			dex.add("Gary", "1212121 Lane Way", "", "Fullerton", "CA", 92831, "US");
			dex.add("Larry", "1212122 Lane Road", "", "Fullerton", "CA", 92831, "US");
			dex.add("Harry", "1212123 Lane Place", "", "Fullerton", "CA", 92831, "US");
			dex.add("Harry", "1212123 Lane Place", "", "Fullerton", "CA", 92831, "US");
			dex.add("Sally", "1212124 Lane Blvd", "", "Fullerton", "CA", 92831, "US");
			
		}, 1, "Add duplicates to the Rolodex"
	);
}


//
void testCopyAssignment(Tests& tests)
{
	//
	auto t = tests.createTest("Copy/Assignment");
	
	t->setFixedPointsPossible(3);
	t->setNormalizedPointsPossibleTarget(5);
	
	//
	t->assertNoException(
		[t]()
		{
			//
			auto t1 = createWordTable();
			auto t2 = t1;
			auto t3(t1);
			
			//
			t->assertTrue(checkTablesEqual<std::string>(t2, t1, true), 1, "Check hash table assignment operator");
			t->assertTrue(checkTablesEqual<std::string>(t3, t1, true), 1, "Check hash table copy CTOR");
			
		}, 1, "Hash Table Copy CTOR and Assignment Operator"
	);
}


//
void testMemoryLeaks(Tests& tests)
{
	//
	auto t = tests.createTest("Memory Leaks");
	
	//
	t->setFixedPointsPossible(11);
	t->setNormalizedPointsPossibleTarget(5);
	
	//
	t->assertNoException(
		[t]()
		{
			//
			string stdout, stderr, message;
			bool leakCheckResult = PuhPTests::Memory::checkMemoryLeaks
			(
				{"make", "leak-checker"},
				"leak-checker",
				stdout, stderr, message
			);
			
			//
			if ( !leakCheckResult ) {
				t->log("Leak Check Result :: STDOUT\n" + stdout);
				t->log("Leak Check Result :: STDERR\n" + stderr);
			}
			t->assertTrue(leakCheckResult, 10, "Checking for memory leaks: " + message);
			
		}, 1, "Memory leaks"
	);
}


//
void testLeaderboard(Tests& tests)
{
	//
	auto t = tests.createTest("Leaderboard");
	
	t->setFixedPointsPossible(1);
	t->setNormalizedPointsPossibleTarget(1);
	
	//
	t->assertNoException(
		[&tests, t]()
		{
			//
			MyHashTable<int> table(100000);
			
			std::vector<unsigned long long int (MyHashTable<int>::*)(std::string) const> customHashFunctions =
			{
				&MyHashTable<int>::myCustomHashFunction1,
				&MyHashTable<int>::myCustomHashFunction2,
				&MyHashTable<int>::myCustomHashFunction3,
				&MyHashTable<int>::myCustomHashFunction4
			};
			
			//
			std::map<
				int, std::map<unsigned long long int, bool>
			> existing_codes;
			
			long n_collisions[4] = {0, 0, 0, 0};
			long worst_possible_n_collisions = g_words.size() - 1;
			long practical_best_n_collisions = 38722;	// from std::hash
			long word_variant_hash_differences[4] = {0, 0, 0, 0};
			double word_variant_hash_scores[4] = {0.0, 0.0, 0.0, 0.0};
			double collision_scores[4] = {0.0, 0.0, 0.0, 0.0};
			
			bool is_midsquare_hash[4] = {true, true, true, true};
			bool is_std_hash[4] = {true, true, true, true};
			std::hash<std::string> stdHasher;
			
			unsigned long long int ideal_variant_difference = 0;
			// unsigned long long int practical_variant_best_difference = 4219161;	// from std::hash
			
			double final_score[4] = {0.0, 0.0, 0.0, 0.0};
			
			//	Attempt to guess each hash function's quality by
			//	testing it against our large word list and
			//	measuring some metrics
			for ( string word : g_words ) {
				
				//	Generate hash codes from each function and track the resulting collisions
				unsigned long long int codes[4];
				codes[0] = table.myCustomHashFunction1(word);
				codes[1] = table.myCustomHashFunction2(word);
				codes[2] = table.myCustomHashFunction3(word);
				codes[3] = table.myCustomHashFunction4(word);
				for ( int function_index = 0; function_index < 4; function_index++ ) {
					
					//
					unsigned long long int code = codes[function_index];
					
					//	Make sure we're not using frikkin std::hash
					//	or other cheats
					if ( code != stdHasher(word) % table.capacity() ) {
						is_std_hash[function_index] = false;
					}
					if ( code != table.midSquareHash(word) % table.capacity() ) {
						is_midsquare_hash[function_index] = false;
					}
					
					//	Possibly increase the known number of collisions for this hash function
					if ( existing_codes[function_index].find(code) == existing_codes[function_index].end() ) {
						existing_codes[function_index][code] = true;
					}
					else {
						n_collisions[function_index]++;
					}
				}
				
				//	Make tiny variants of the current word and compute how similar their hashes are to the original
				auto word_variants = makeTinyWordVariants(word);
				for ( int function_index = 0; function_index < 4; function_index++ ) {
					
					//
					auto actual_ideal = computeHashOutputSimilarities(
						word, word_variants,
						customHashFunctions[function_index]
					);
					word_variant_hash_differences[function_index] += std::get<0>(actual_ideal);
					
					//
					if ( function_index == 0 ) {
						ideal_variant_difference += std::get<1>(actual_ideal);
					}
				}
			}
			
			//	Compute percent/float scores for each function
			for ( size_t i = 0; i < 4; i++ ) {
				
				auto range = worst_possible_n_collisions - practical_best_n_collisions;
				collision_scores[i] = 1.0 - (	//	yep, i'm inverting
					(n_collisions[i] - practical_best_n_collisions)
					/
					static_cast<double>(range)
				);
				
				word_variant_hash_scores[i] = (
					word_variant_hash_differences[i]
					/
					static_cast<double>(ideal_variant_difference)
					//static_cast<double>(practical_variant_best_difference)
				);
				
				//	Combine the scores into a weighted final score
				final_score[i] = (
					collision_scores[i] * 0.5
					+ word_variant_hash_scores[i] * 0.5
				);
			}
			
			//	Print a quick little summary
			t->log("Worst possible number of collisions: " + std::to_string(worst_possible_n_collisions));
			t->log("Best possible word-variant difference is: " + std::to_string(ideal_variant_difference));
			//t->log("Practical best word-variant difference is: " + std::to_string(practical_variant_best_difference));
			for ( size_t i = 0; i < 4; i++ ) {
				t->log
				(
					"myCustomHashFunction" + std::to_string( i + 1)
					+ ": Small variant bit difference score="
					+ std::to_string(word_variant_hash_differences[i])
					+ " (" + std::to_string(word_variant_hash_scores[i] * 100) + "%)"
				);
				t->log
				(
					"myCustomHashFunction" + std::to_string( i + 1)
					+ ": n_collisions=" + std::to_string(n_collisions[i])
					+ " (" + std::to_string(collision_scores[i] * 100) + "%)"
				);
			}
			t->log("Final weighted scores:");
			for ( size_t i = 0; i < 4; i++ ) {
				t->log
				(
					"Custom function #" + std::to_string( i + 1 )
					+ ": " + std::to_string(final_score[i] * 100) + "%"
				);
			}
			
			//	Determine the best hash function
			int best_function_index = 0;
			long best_n_collisions = n_collisions[0];
			double best_collision_score = collision_scores[0];
			long best_variant_differences = word_variant_hash_differences[0];
			double best_variant_hash_scores = word_variant_hash_scores[0];
			double best_final_score = final_score[0];
			for ( size_t i = 1; i < 4; i++ ) {
				if ( final_score[i] > best_final_score ) {
					best_function_index = i;
					best_n_collisions = n_collisions[i];
					best_collision_score = collision_scores[i];
					best_variant_differences = word_variant_hash_differences[i];
					best_variant_hash_scores = word_variant_hash_scores[i];
					best_final_score = final_score[i];
				}
			}
			cout
				<< "==> Best is function #" << (best_function_index + 1)
				<< " with a final score of " << (static_cast<int>(best_final_score * 100)) << "%"
				<< endl
				;
			cout << "(sending to Leaderboard)" << endl;
			
			//
			bool found_cheat = false;
			for ( bool b : is_std_hash ) {
				found_cheat = (found_cheat || b);
			}
			for ( bool b : is_midsquare_hash ) {
				found_cheat = (found_cheat || b);
			}
			if ( found_cheat ) {
				throw std::runtime_error(
					"Don't try to cheat the Leaderboard by using pre-made functions or reusing our primary hashing function. Shame on you!"
				);
			}
			
			//
			auto board = tests.createLeaderboard();
			board->setSortDirection(LeaderboardSortDirection::Descending);
			board->addEntry("Score", best_final_score * 100);
			board->addEntry("Collisions", best_n_collisions);
			board->addEntry("Collisions Score", best_collision_score);
			board->addEntry("Variant difference", best_variant_differences);
			board->addEntry("Variant Score", best_variant_hash_scores);
			tests.setLeaderboard(board);
			
		}, 1, "Extra point for not crashing the Leaderboard test"
	);
}















